In [132]:
import numpy as np

In [133]:
stats = np.array([[1, 2, 3], [4, 5, 6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

**Exercício:** encontre a média e o desvio padrão da matriz, sabendo que os métodos são representados por `np.mean()` e `np.std()`, respectivamente.

In [134]:
# Média
stats.mean()

3.5

In [135]:
# Desvio Padrão
stats.std()

1.707825127659933

_________________
**Exercício:** Realize a soma para cada linha e para cada coluna:

In [136]:
# Por linha
stats.sum(1)

array([ 6, 15])

In [137]:
# Por coluna
stats.sum(0)

array([5, 7, 9])

### Operador OR
Similar ao `or`, só que devemos utilizar `|`. <br><br>
**Exercício:** Seleciona os valores que são iguais a 1 ou maiores do que 20

In [138]:
mat = np.array([1, 10, 20, 30]).reshape(2, 2)
mat

array([[ 1, 10],
       [20, 30]])

In [139]:
mat[(mat == 1) | (mat > 20)]

array([ 1, 30])

## Exercícios

1 - Selecione todos os valores ímpares do seguinte array:  <br>
array = [1, 2, 3, 4, 5, 6, 7, 8, 9] <br>


In [140]:
array = np.array([1,2,3,4,5,6,7,8,9])
array[array % 2 != 0]

array([1, 3, 5, 7, 9])

2 - Substitua os valores ímpares do seguinte array por 0:  <br>
array = [1, 2, 3, 4, 5, 6, 7, 8, 9] <br>

In [141]:
array[array % 2 != 0] = 0
array

array([0, 2, 0, 4, 0, 6, 0, 8, 0])

3 - Considere o dataset da iris disponível em: 
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'<br> 
Nesse dataset temos as seguintes informações:<br> 
   * Coluna 1. sepal length em cm<br> 
   * Coluna 2. sepal width em cm<br> 
   * Coluna 3. petal length em cm<br> 
   * Coluna 4. petal width em cm<br> 
   * Coluna 5. classe: 
                -- Iris Setosa 
                -- Iris Versicolour 
                -- Iris Virginica 
                
Utilizando o método `np.genfromtxt()`, importe as 4 primeiras colunas do dataset do íris e print as 10 primeiras linhas <br>

In [142]:
df_iris = np.genfromtxt('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data',
                        delimiter=",",
                        usecols=[0,1,2,3]) # Seleciona algumas colunas, que são 4
df_iris[:10]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

4 - Calcule a média, mediana e desvio padrão da coluna sepallenght

In [143]:
# Coluna 0 é a Sepal Length
media = np.median(df_iris[:,0])
print(f"A média da sepal length é {media}")

mediana = np.mean(df_iris[:,0])
print(f"A mediana da sepal length é {mediana}")

desvio = np.std(df_iris[:,0])
print(f"O desvio padrão da sepal length é {desvio}")

A média da sepal length é 5.8
A mediana da sepal length é 5.843333333333334
O desvio padrão da sepal length é 0.8253012917851409


5 - Filtre a matriz para conter apenas dados nos quais petallength (3ª coluna) > 1.5 e sepallength (1ª coluna) < 5.0

In [144]:
df_iris[(df_iris[:,2] > 1.5) & (df_iris[:,0] < 5)]

array([[4.8, 3.4, 1.6, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7]])

6 - Esse dataset possui nans?

In [145]:
np.isnan(df_iris).any() # Todos os valores estão preenchidos

False

7 - Crie uma coluna de volume sabendo que ele pode ser calculado por (pi x petallength x sepal_length^2)/3

In [146]:
import math

volume = math.pi * df_iris[:,2] * (df_iris[:,0] ** 2) / 3
volume = volume.reshape(-1,1)

df_iris = np.hstack([df_iris, volume])
df_iris[:10,:]

array([[ 5.1       ,  3.5       ,  1.4       ,  0.2       , 38.13265163],
       [ 4.9       ,  3.        ,  1.4       ,  0.2       , 35.20049849],
       [ 4.7       ,  3.2       ,  1.3       ,  0.2       , 30.07237208],
       [ 4.6       ,  3.1       ,  1.5       ,  0.2       , 33.23805027],
       [ 5.        ,  3.6       ,  1.4       ,  0.2       , 36.65191429],
       [ 5.4       ,  3.9       ,  1.7       ,  0.4       , 51.91167701],
       [ 4.6       ,  3.4       ,  1.4       ,  0.3       , 31.02218026],
       [ 5.        ,  3.4       ,  1.5       ,  0.2       , 39.26990817],
       [ 4.4       ,  2.9       ,  1.4       ,  0.2       , 28.38324243],
       [ 4.9       ,  3.1       ,  1.5       ,  0.1       , 37.71481981]])